-- FunDom — fundamental domains of congruence subgroups of SL₂(ℤ).
-- Copyright (C) 2026 RJ Acuña. Mode 1 derives from Helena A. Verrill's
-- FunDomain (Copyright (C) 2001, GPL-2.0-or-later); see java/ and README.md.
-- SPDX-License-Identifier: GPL-3.0-or-later
-- | From generators to the coset action: a Todd–Coxeter enumeration of
-- @⟨generators⟩@ in @PSL₂(ℤ) = ⟨S, R | S², R³⟩@.
--
-- Each generator, as a reduced word, is traced as a loop at the base
-- coset, creating cosets as it goes; the end is identified with the base.
-- Identifications are propagated (a coset has at most one S-neighbour and
-- one R-image), and the relation R³ = 1 is imposed by closing R-chains:
-- whenever @v → w → x@ under R, @x → v@. Because the presentation is a
-- free product of finite groups, no other cosets ever need defining: when
-- the process stops, either every coset has an S-neighbour and an R-image
-- — the table is complete, and by the correctness of coset enumeration it
-- is the action on @⟨generators⟩\\PSL₂(ℤ)@ — or some coset lacks one, and
-- the Schreier graph continues from there into an infinite hanging tree:
-- the subgroup has infinite index.
module Modular.Coset
  ( PermRep(..), Enumeration(..), enumerateWords, enumerateMatrices
  , actLetter, actWord, permL, permR, permOf, cycleLengths, generalisedLevel
  , schreierGenerators
  ) where

import Data.Array.Unboxed
import qualified Data.IntMap.Strict as IM
import Flint.SL2
import Modular.Word

-- | The action of S and R on the right cosets @0 .. n−1@, with @0@ the
-- subgroup itself.
data PermRep = PermRep
  { prSize :: !Int
  , prS    :: UArray Int Int
  , prR    :: UArray Int Int
  }

data Enumeration
  = Finite PermRep
  | Infinite Int        -- ^ the number of cosets in the incomplete table

-- The table --------------------------------------------------------------------

data Tab = Tab
  { tNext   :: !Int
  , tParent :: IM.IntMap Int    -- ^ union–find; absent means representative
  , tS      :: IM.IntMap Int    -- ^ S-neighbour, keyed by representative
  , tR      :: IM.IntMap Int    -- ^ R-image
  , tRi     :: IM.IntMap Int    -- ^ R-preimage
  }

emptyTab :: Tab
emptyTab = Tab 1 IM.empty IM.empty IM.empty IM.empty

rep :: Tab -> Int -> Int
rep t v = case IM.lookup v (tParent t) of
  Nothing -> v
  Just p  -> rep t p

look :: (Tab -> IM.IntMap Int) -> Tab -> Int -> Maybe Int
look f t v = rep t <$> IM.lookup (rep t v) (f t)

-- | Set an edge from a representative, with its inverse edge.
setEdge :: Letter -> Int -> Int -> Tab -> Tab
setEdge LS  u v t = t { tS  = IM.insert u v (IM.insert v u (tS t)) }
setEdge LR  u v t = t { tR  = IM.insert u v (tR t),  tRi = IM.insert v u (tRi t) }
setEdge LRi u v t = t { tRi = IM.insert u v (tRi t), tR  = IM.insert v u (tR t) }

edgeOf :: Letter -> Tab -> Int -> Maybe Int
edgeOf LS  = look tS
edgeOf LR  = look tR
edgeOf LRi = look tRi

-- | Identify two cosets and everything that follows from it.
coincide :: Tab -> Int -> Int -> Tab
coincide t0 a0 b0 = go t0 [(a0, b0)]
  where
    go t [] = t
    go t ((a, b) : queue) =
      let ra = rep t a
          rb = rep t b
      in if ra == rb then go t queue else
           let -- merge rb into ra: move rb's edges over, queueing clashes
               t1 = t { tParent = IM.insert rb ra (tParent t) }
               (t2, q2) = moveEdge tS  LS  ra rb t1 queue
               (t3, q3) = moveEdge tR  LR  ra rb t2 q2
               (t4, q4) = moveEdge tRi LRi ra rb t3 q3
           in go t4 q4
    -- rb's edge of one kind, if any: either becomes ra's, or clashes with ra's
    moveEdge f l ra rb t queue = case IM.lookup rb (f t) of
      Nothing -> (t, queue)
      Just x  ->
        let x' = rep t x
        in case IM.lookup ra (f t) of
             Nothing -> (setEdge l ra x' t, queue)
             Just y  -> (t, (x', rep t y) : queue)

-- | Trace a word from the base as a loop, creating cosets along the way.
traceLoop :: Tab -> GWord -> Tab
traceLoop t0 w = let (t, end) = foldl' step (t0, rep t0 0) w in coincide t end (rep t 0)
  where
    step (t, v) l = case edgeOf l t v of
      Just u  -> (t, u)
      Nothing -> let n = tNext t
                     t' = setEdge l (rep t v) n (t { tNext = n + 1 })
                 in (t', n)

-- | Close every R-chain: v → w → x forces x → v.
closeR :: Tab -> Tab
closeR t0 = loop t0
  where
    loop t =
      let reps = [ v | v <- [0 .. tNext t - 1], rep t v == v ]
          t' = foldl' close t reps
      in if same t t' then t' else loop t'
    close t v
      | rep t v /= v = t
      | otherwise = case look tR t v of
          Nothing -> t
          Just w  -> case look tR t w of
            Nothing -> t
            Just x  -> case look tR t x of
              Nothing -> setEdge LR x (rep t v) t
              Just y  -> if y == rep t v then t else coincide t y v
    same a b = tParent a == tParent b && tS a == tS b && tR a == tR b

-- | Enumerate the cosets of the subgroup generated by words.
enumerateWords :: [GWord] -> Enumeration
enumerateWords ws =
  let t = closeR (foldl' traceLoop emptyTab (map reduceW ws))
      reps = [ v | v <- [0 .. tNext t - 1], rep t v == v ]
      complete = all (\v -> look tS t v /= Nothing && look tR t v /= Nothing) reps
  in if not complete then Infinite (length reps) else
       let base   = rep t 0
           order  = base : filter (/= base) reps
           number = IM.fromList (zip order [0 ..])
           idx v  = number IM.! rep t v
           n      = length order
           arr f  = listArray (0, n - 1) [ maybe (error "enumerateWords: incomplete") idx (look f t v) | v <- order ] :: UArray Int Int
       in Finite (PermRep n (arr tS) (arr tR))

enumerateMatrices :: [SL2] -> Enumeration
enumerateMatrices = enumerateWords . map wordOf

-- The action ------------------------------------------------------------------------

actLetter :: PermRep -> Letter -> Int -> Int
actLetter pr LS  c = prS pr ! c
actLetter pr LR  c = prR pr ! c
actLetter pr LRi c = prRi ! c
  where prRi = inversePerm (prR pr)

actWord :: PermRep -> GWord -> Int -> Int
actWord pr w c = foldl' (flip (actLetter pr)) c w

inversePerm :: UArray Int Int -> UArray Int Int
inversePerm p = array (bounds p) [ (p ! i, i) | i <- indices p ]

-- | The permutation of a word, as an array.
permOf :: PermRep -> GWord -> UArray Int Int
permOf pr w = listArray (0, prSize pr - 1) [ actWord pr w c | c <- [0 .. prSize pr - 1] ]

-- | Hsu's L = [1 1; 0 1] = T = S·R and R = [1 0; 1 1] = S·R⁻¹.
permL, permR :: PermRep -> UArray Int Int
permL pr = permOf pr [LS, LR]
permR pr = permOf pr [LS, LRi]

cycleLengths :: UArray Int Int -> [Int]
cycleLengths p = go (indices p) IM.empty
  where
    go [] _ = []
    go (i : is) seen
      | IM.member i seen = go is seen
      | otherwise = let cyc = i : takeWhile (/= i) (drop 1 (iterate (p !) i))
                    in length cyc : go is (foldr (\c -> IM.insert c ()) seen cyc)

-- | The lcm of the cusp widths: the order of the permutation of T.
generalisedLevel :: PermRep -> Int
generalisedLevel pr = foldl' lcm 1 (cycleLengths (permL pr))

-- | Schreier generators of the subgroup from its coset action: with a
-- transversal of words @t_c@ from a spanning tree, @t_c · x · t_{c·x}⁻¹@
-- for every coset @c@ and letter @x ∈ {S, R}@. Used to round-trip a
-- permutation representation through the enumeration.
schreierGenerators :: PermRep -> [SL2]
schreierGenerators pr = filter (/= identity)
  [ wordMat (reduceW (tv c ++ [x] ++ invWord (tv (actLetter pr x c)))) | c <- [0 .. n - 1], x <- [LS, LR] ]
  where
    n = prSize pr
    -- breadth-first transversal
    tv c = trans IM.! c
    trans = go (IM.singleton 0 []) [0]
      where
        go m [] = m
        go m (c : queue) =
          let new = [ (d, trans' ++ [x]) | x <- [LS, LR], let d = actLetter pr x c, not (IM.member d m), let trans' = m IM.! c ]
              m' = foldl' (\acc (d, w) -> IM.insert d w acc) m new
          in go m' (queue ++ map fst new)
